# product-service/.github/workflows/product-service-ci.yml
name: Product Service CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27018:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..10}; do
            if mongo --host localhost --port 27018 --eval 'db.runCommand({ ping: 1 })' > /dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "MongoDB is not ready yet, waiting..."
            sleep 10
          done

      - name: Set environment variables
        run:
          echo "DB_URL=mongodb://localhost:27018/product-service" >> $GITHUB_ENV

      - name: Build and test Product Service
        run: |
          mvn -B -f pom.xml clean package
          mvn -B

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ProductService-Package
          path: target/*.jar