# inventory-service/.github/workflows/inventory-service-ci.yml
name: Inventory Service CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: inventory_service_db
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..10}; do
            if pg_isready -h localhost -p 5434 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "PostgreSQL is not ready yet, waiting..."
            sleep 10
          done

      - name: Set environment variables
        run: |
          echo "DB_URL=jdbc:postgresql://localhost:5434/inventory_service_db" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV

      - name: Build and test Inventory Service
        run: |
          mvn -B -f pom.xml clean package
          mvn -B -f pom.xml test -Dspring.datasource.url=${{ env.DB_URL }} \
                                 -Dspring.datasource.username=${{ env.DB_USER }} \
                                 -Dspring.datasource.password=${{ env.DB_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InventoryService-Package
          path: target/*.jar